amazon:
  aws:
    region: us-east-1
  dynamodb:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
   
cloud:
  aws:
   region:
    static : us-east-1
   
   stack:
    auto : false 
      
 
 
katharsis:
  resourcePackage: com.poc.serviceRepository
  domainName: http://localhost:9090/cashBackFinder
  pathPrefix: /api
server:
#  port: 5000
  servlet:
    context-path: /cashBackFinder
