package com.poc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.katharsis.resource.annotations.JsonApiId;
import io.katharsis.resource.annotations.JsonApiResource;

//@DynamoDBTable(tableName = "Trends")
@JsonApiResource(type = "trends")
public class Trends {

	@JsonApiId
	private int id;
	
	private String company;
	private String retailer;
	private String cashBackPercentage;
	
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
//	@DynamoDBAttribute
	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
	
//	@DynamoDBAttribute
	public String getRetailer() {
		return retailer;
	}

	public void setRetailer(String retailer) {
		this.retailer = retailer;
	}
	
//	@DynamoDBAttribute
	public String getCashBackPercentage() {
		return cashBackPercentage;
	}

	public void setCashBackPercentage(String cashBackPercentage) {
		this.cashBackPercentage = cashBackPercentage;
	}

}
